config/routes.rb
Rails.application.routes.draw do
  
  resources :show_map

  resources :items do
    collection do
      get :items_suppliers
      get :insert
      get :suppliers
    end
  end

 resources :map_order do
  collection do
    post :creates
  end
 end

  get 'purchase_orders/index'

  resources :inventory_items
  resources :purchase_orders do
    collection do 
      get :get_data
    end
  end

end

app/models/account_object.rb
class AccountObject < ActiveRecord::Base
  establish_connection DB_CONF
  self.table_name = 'AccountObject'
  has_many :item, foreign_key: :supplier_id
  has_one :account_object, primary_key: :AccountObjectID
end

app/models/container_type.rb
class ContainerType < ActiveRecord::Base
  acts_as_paranoid
end

app/models/high_score.rb
class HighScore < ActiveRecord::Base
end

app/models/inventory_item.rb
class InventoryItem < ActiveRecord::Base
  establish_connection DB_CONF
  self.table_name = 'InventoryItem'
end

app/models/item.rb
class Item < ActiveRecord::Base
  acts_as_paranoid
end

app/models/map_item.rb
class MapItem < ActiveRecord::Base
  self.table_name = 'map_item'
  has_many :pu_order_detail ,foreign_key: :InventoryItemID, primary_key: :ItemID
end

app/models/map_purchase.rb
class MapPurchase < ActiveRecord::Base
  has_many :purchase_order, foreign_key: :RefID, primary_key: :RefID
  has_many :map_item, foreign_key: :map_purchase_id
end

app/models/pu_order_detail.rb
class PuOrderDetail < ActiveRecord::Base
  establish_connection DB_CONF
  self.table_name = 'PuOrderDetail'

  belongs_to :purchase_order, foreign_key: :RefID
  has_one :item , foreign_key: :item_id, primary_key: :InventoryItemID
end

app/models/purchase_order.rb
class PurchaseOrder < ActiveRecord::Base
  establish_connection DB_CONF
  self.table_name = 'PUOrder'

  enum Status: ["Chưa thực hiện", "Đang thực hiện", "Hoàn thành" ]

  has_many :pu_order_detail, foreign_key: :RefID
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  establish_connection DB_CONF
  self.table_name = 'Unit'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/high_scores_controller.rb
class HighScoresController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  end

  def show
    @supplier = AccountObject.where(AccountObjectID: params[:id])
    @items = InventoryItem.all
    @selected_items = @supplier[0].item
    #binding.pry
  end

  def insert
     #binding.pry
    @list_items = InventoryItem.where(InventoryItemID: params[:list_items])
    @list_items.each do |item|
      params_create = {item_id: item.InventoryItemID,
                       item_code: item.InventoryItemCode,
                       supplier_id: params[:supplier_id]}
      Item.create(params_create)
    end
    redirect_to item_path(params[:supplier_id])
  end

  def suppliers
    @suppliers = AccountObject.all
  end
end

app/controllers/map_order_controller.rb
class MapOrderController < ApplicationController
  def index
    @purchase_order = PurchaseOrder.where(status: [0, 1]).order(:RefDate)
  end

  def create
    @list_order = PurchaseOrder.includes(:pu_order_detail).where(RefID: params[:list_orders])
  end

  def creates
    # binding.pry
    map_id = Time.now.strftime("%Y%d%m%H%M%S")
    params[:Pu].each do |pu|
      MapPurchase.create(map_id: map_id , RefID: pu[:RefID], date_map: Time.now.strftime("%Y-%d-%m %H:%M:%S %Z"))
      pu[:Item].each do |item|
        MapItem.create(ItemID: item[:InventoryItemID], map_purchase_id: MapPurchase.find_by(RefID: pu[:RefID]).id, quantity: item[:quantity]  )
      end
    end
  end

end

app/controllers/purchase_orders_controller.rb
class PurchaseOrdersController < ApplicationController
  
  def index
    @purchase_orders =  PurchaseOrder.all
  end

  def show
    @Units = Unit.all
    @purchase_order =  PurchaseOrder.where(RefID: params[:id])
    @detail_pus = @purchase_order[0].pu_order_detail
  end

  def get_data
    @inventory_items = InventoryItem.all
    @inventory_items.each do |item|
      params_create = {item_id: item.InventoryItemID,
                       item_code: item.InventoryItemCode}
      Item.create(params_create)
    end
    redirect_to purchase_order_path(params[:format])
  end


end

app/controllers/show_map_controller.rb
class ShowMapController < ApplicationController
  def index
    @list_map = MapPurchase.all.map(&:map_id).uniq
    if params[:list_map].nil?
      @list_order = MapPurchase.where( map_id: @list_map.first)
    else
      @list_order = MapPurchase.where( map_id: params[:list_map])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/high_scores_helper.rb
module HighScoresHelper
end

app/helpers/inventory_items_helper.rb
module InventoryItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/map_order_helper.rb
module MapOrderHelper

  def show_unit(unit_id)
    Unit.where(UnitID: unit_id)[0].try(:UnitName)
  end

  def volume(volume, quantity)
    volume = volume.nil? ? 0 : volume
    volume*quantity
  end

  def weight(weight, quantity)
    weight = weight.nil? ? 0 : weight
    weight*quantity
  end
end

app/helpers/purchase_orders_helper.rb
module PurchaseOrdersHelper
end

app/helpers/show_map_helper.rb
module ShowMapHelper
end

app/views/purchase_orders/index.html.erb
<section class="content">
  <div class="wrapper">
<h1 align="center">Mua Hang</h1>
<table id="example" class="display responsive nowrap" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Tình trạng</th>
      <th>Ngày đơn hàng</th>
      <th>Số đơn hàng</th>
      <th>Ngày giao hàng</th>
      <th>Nhà cung cấp</th>
      <th>Số tiền</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @purchase_orders.each do |purchase_order|%>
      <tr>
          <td><%= purchase_order.Status%></td>
          <td><%= purchase_order.RefDate.strftime("%d-%m-%Y")%></td>
          <td><%= purchase_order.RefNo%></td>
          <td><%= purchase_order.ReceiveDate.strftime("%d-%m-%Y")%></td>
          <td><%= purchase_order.AccountObjectName%></td>
          <td><%= purchase_order.TotalAmount%></td>
          <td><%= button_to "Chi tiết", purchase_order_path(purchase_order.RefID), method: :get%></td>
      </tr>
      <%end%>
  </tbody>
</table>
</div>
</section>

app/views/purchase_orders/show.html.erb
  <section class="content">
    <div class="wrapper">
      <div class="panel panel-default login-form">
          <div class="panel-heading">
            <h3 class="panel-title text-center">
              <i class="glyphicon glyphicon-glass"><b style="font-size:18px;"> Đơn hàng: <%=@purchase_order[0].RefNo %></b></i>
            </h3>
          </div>
          <div class="main panel-body">
            <div class="main-show">
                <table style="width:90%;font-size:18px;">
                  <tr>
                    <td colspan="3">Tình trạng: <font style="color:red"><%=@purchase_order[0].Status %></font></td>
                  </tr>
                  <tr>
                    <td>Nhà cung cấp: <%=@purchase_order[0].AccountObjectName %></td>
                    <td>Địa chỉ: <%=@purchase_order[0].AccountObjectAddress %></td>
                    <td>SDT: <%=@purchase_order[0].AccountObjectTaxCode %></td>
                    <td>Email: <%= %></td>
                  </tr>
                  <tr>
                    <td>Ngày đơn hàng: <%=@purchase_order[0].RefDate.strftime("%d-%m-%Y") %></td>
                    <td colspan="3">Ngày giao hàng: <%=@purchase_order[0].ReceiveDate.strftime("%d-%m-%Y") %></td>
                  </tr>
                  <tr>
                    <td>Diễn giải: <%=@purchase_order[0].JournalMemo %></td>
                    <td colspan="3">Số tiền: <%=@purchase_order[0].TotalAmount %></td>
                  </tr>
                  <tr>
                    <td>Tổng khối lượng: xxx</td>
                    <td colspan="3">Tổng thể tích: xxx</td>
                  </tr>
                </table>
                
              </div>
          </div>
      </div>


<div class="panel panel-default login-form">
  <div class="row-main panel-body">
    <% @detail_pus.each do |detail_pu|%>

    <div class="panel panel-default login-form">
          <div class="panel-heading">
            <h3 class="panel-title">
              <b style="font-size:16px;">Mã hàng: <%= detail_pu.InventoryItemID%></b>
            </h3>
          </div>
          <div class="panel-body">
            <div class="row-main-solid">
        <table style="width:90%;font-size:15px;">
          <tr>
            <td colspan="3">Tên hàng: <%= detail_pu.Description%></td>
          </tr>
          <tr>
            <td>Số lượng: <%= detail_pu.Quantity%></td>
            <td colspan="3">
              Đơn vị tính:
              <%= select("post", "person_id", @Units.collect {|p| [ p.UnitName, p.UnitID ] }, { selected: detail_pu.UnitID}, class: "form-control")%>
            </td>
          </tr>
          <tr>
            <td>Số lượng nhận: <input type="text" value="<%= detail_pu.QuantityReceipt%>", class= "form-control"/></td>
            <td>Đơn giá: <input type="text" value="<%= detail_pu.UnitPrice%>" , class= "form-control"/></td>
            <td colspan="2">Thành tiền: <%= detail_pu.Amount%></td>
          </tr>
          <tr>
            <td>Tỉ lệ chiết khấu: <input type="text" value="<%= detail_pu.DiscountRate%>", class= "form-control"/></td>
            <td>Tiền chiết khấu: <input type="text" value="<%= detail_pu.DiscountAmount%>", class= "form-control pull-left"/></td>
            <td>Tỉ lệ GTGT: <input type="text" value="<%= detail_pu.VATRate%>", class= "form-control"/></td>
            <td>Tiền GTGT: <input type="text" value="<%= detail_pu.VATAmount%>", class= "form-control"/></td>
          </tr>
          <tr>
            <td>Thể tích: xxx</td>
            <td colspan="3">Khối lượng: xxx</td>
          </tr>
        </table>
      </div>
          </div>
      </div>
      <% end %>
  </div>
</div>
      
  
    <center style="margin-top:10px;">
    <%= link_to "Quay lại", purchase_orders_path, class: "btn btn-primary", onclick: "location"%>

  <br>
  <br>
  <br>
    <%= button_to "Get Data", get_data_purchase_orders_path(@purchase_order[0].RefID), method: :get,  class: "btn btn-primary", onclick: "location"%>
</div>
</section>