config/routes.rb
Rails.application.routes.draw do
  
  resources :show_map

  resources :items do
    collection do
      get :items_suppliers
      get :insert
      get :suppliers
    end
  end

 resources :map_order do
  collection do
    post :creates
  end
 end

  get 'purchase_orders/index'

  resources :inventory_items
  resources :purchase_orders do
    collection do 
      get :get_data
    end
  end

end

app/models/account_object.rb
class AccountObject < ActiveRecord::Base
  establish_connection DB_CONF
  self.table_name = 'AccountObject'
  has_many :item, foreign_key: :supplier_id
  has_one :account_object, primary_key: :AccountObjectID
end

app/models/container_type.rb
class ContainerType < ActiveRecord::Base
  acts_as_paranoid
end

app/models/high_score.rb
class HighScore < ActiveRecord::Base
end

app/models/inventory_item.rb
class InventoryItem < ActiveRecord::Base
  establish_connection DB_CONF
  self.table_name = 'InventoryItem'
end

app/models/item.rb
class Item < ActiveRecord::Base
  acts_as_paranoid
end

app/models/map_item.rb
class MapItem < ActiveRecord::Base
  self.table_name = 'map_item'
  has_many :pu_order_detail ,foreign_key: :InventoryItemID, primary_key: :ItemID
end

app/models/map_purchase.rb
class MapPurchase < ActiveRecord::Base
  has_many :purchase_order, foreign_key: :RefID, primary_key: :RefID
  has_many :map_item, foreign_key: :map_purchase_id
end

app/models/pu_order_detail.rb
class PuOrderDetail < ActiveRecord::Base
  establish_connection DB_CONF
  self.table_name = 'PuOrderDetail'

  belongs_to :purchase_order, foreign_key: :RefID
  has_one :item , foreign_key: :item_id, primary_key: :InventoryItemID
end

app/models/purchase_order.rb
class PurchaseOrder < ActiveRecord::Base
  establish_connection DB_CONF
  self.table_name = 'PUOrder'

  enum Status: ["Chưa thực hiện", "Đang thực hiện", "Hoàn thành" ]

  has_many :pu_order_detail, foreign_key: :RefID
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  establish_connection DB_CONF
  self.table_name = 'Unit'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/high_scores_controller.rb
class HighScoresController < ApplicationController
  def index
  end
end

app/controllers/inventory_items_controller.rb
class InventoryItemsController < ApplicationController
  def index
    @inventorys = InventoryItem.all
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  end

  def show
    @supplier = AccountObject.where(AccountObjectID: params[:id])
    @items = InventoryItem.all
    @selected_items = @supplier[0].item
    #binding.pry
  end

  def insert
     #binding.pry
    @list_items = InventoryItem.where(InventoryItemID: params[:list_items])
    @list_items.each do |item|
      params_create = {item_id: item.InventoryItemID,
                       item_code: item.InventoryItemCode,
                       supplier_id: params[:supplier_id]}
      Item.create(params_create)
    end
    redirect_to item_path(params[:supplier_id])
  end

  def suppliers
    @suppliers = AccountObject.all
  end
end

app/controllers/map_order_controller.rb
class MapOrderController < ApplicationController
  def index
    @purchase_order = PurchaseOrder.where(status: [0, 1]).order(:RefDate)
  end

  def create
    @list_order = PurchaseOrder.includes(:pu_order_detail).where(RefID: params[:list_orders])
  end

  def creates
    # binding.pry
    map_id = Time.now.strftime("%Y%d%m%H%M%S")
    params[:Pu].each do |pu|
      MapPurchase.create(map_id: map_id , RefID: pu[:RefID], date_map: Time.now.strftime("%Y-%d-%m %H:%M:%S %Z"))
      pu[:Item].each do |item|
        MapItem.create(ItemID: item[:InventoryItemID], map_purchase_id: MapPurchase.find_by(RefID: pu[:RefID]).id, quantity: item[:quantity]  )
      end
    end
  end

end

app/controllers/show_map_controller.rb
class ShowMapController < ApplicationController
  def index
    @list_map = MapPurchase.all.map(&:map_id).uniq
    if params[:list_map].nil?
      @list_order = MapPurchase.where( map_id: @list_map.first)
    else
      @list_order = MapPurchase.where( map_id: params[:list_map])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/high_scores_helper.rb
module HighScoresHelper
end

app/helpers/inventory_items_helper.rb
module InventoryItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/map_order_helper.rb
module MapOrderHelper

  def show_unit(unit_id)
    Unit.where(UnitID: unit_id)[0].try(:UnitName)
  end

  def volume(volume, quantity)
    volume = volume.nil? ? 0 : volume
    volume*quantity
  end

  def weight(weight, quantity)
    weight = weight.nil? ? 0 : weight
    weight*quantity
  end
end

app/helpers/purchase_orders_helper.rb
module PurchaseOrdersHelper
end

app/helpers/show_map_helper.rb
module ShowMapHelper
end

app/views/high_scores/index.html.erb
<h1>HighScores#index</h1>
<p>Find me in app/views/high_scores/index.html.erb</p>

app/views/items/items_suppliers.html.erb
<section class="content">
  <div class="wrapper">
    <h1 align="center">Chọn mặt hàng</h1>
    <div class="col-md-8">
      <h4>Multi-select</h4>
      <%= form_tag(insert_items_path, method: :get) do %>

        <%= select_tag 'list_items', options_for_select(@items.collect{ |u| [u.InventoryItemName, u.InventoryItemCode] }), multiple: true , id: :items%>
         <%= submit_tag( "SUBMIT" ) %>
      <% end %>
    </div>
    <button onclick="check()">check</button>
    <p id="demo"></p>
  </div>
</section>

app/views/items/show.html.erb
<section class="content">
  <div class="wrapper">
    <div class="page-header">
      <h1 align="center">Chọn Mặt Hàng</h1>
    </div>
    <div style="display: none">
      <% @selected_items.each do |selected_item| %>
        <input type="hidden" class="selected_item" value="<%=selected_item.item_id%>"><%=selected_item.item_id%></input>
      <%end%>
    </div>
    <div class="select_container">
      <div class="items" style="width: 65%">
        <%= form_tag(insert_items_path, method: :get) do %>
          <%= hidden_field_tag 'supplier_id',  @supplier[0].AccountObjectID %>
          <%= select_tag 'list_items', options_for_select(@items.collect{ |u| [u.InventoryItemName, u.InventoryItemID] }), multiple: true , id: :items%>
      </div>
      <div class="items" style="width: 30%">
      <%= submit_tag( "Chọn", class: "btn btn-primary btn-lg", style:"width: 250px;margin: 0px 0px 10px 32px ;", id: "chon" ) %>
        <% end %>
          <div class="panel panel-primary">
            <div class="panel-heading"><center>Mặt hàng đã chọn</center></div>
            <div class="panel-body-selected" id="test">
            </div>
          </div>
      </div>
    </div>
  </div>
</section>

app/views/items/suppliers.html.erb
<section class="content">
  <div class="wrapper">
    <div class="page-header">
      <h1 align="center">Nhà Cung Cấp</h1>
    </div>
    <table id="example" class="display responsive nowrap" cellspacing="0" width="100%">
      <thead>
        <tr>
          <th>Mã NCC</th>
          <th>Tên NCC</th>
          <th>Địa chỉ</th>
          <th>Số điện thoại</th>
          <th>Email</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @suppliers.each do |supplier|%>
          <tr>
            <td><%= supplier.AccountObjectCode%></td>
            <td><%= supplier.AccountObjectName%></td>
            <td><%= supplier.Address%></td>
            <td><%= supplier.Tel%></td>
            <td><%= supplier.EmailAddress%></td>
            <td><%= button_to "Chi tiết", item_path(supplier.AccountObjectID), method: :get%></td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</section>