config/routes.rb
Rails.application.routes.draw do
  
  resources :show_map

  resources :items do
    collection do
      get :items_suppliers
      get :insert
      get :suppliers
    end
  end

 resources :map_order do
  collection do
    post :creates
  end
 end

  get 'purchase_orders/index'

  resources :inventory_items
  resources :purchase_orders do
    collection do 
      get :get_data
    end
  end

end

app/models/account_object.rb
class AccountObject < ActiveRecord::Base
  establish_connection DB_CONF
  self.table_name = 'AccountObject'
  has_many :item, foreign_key: :supplier_id
  has_one :account_object, primary_key: :AccountObjectID
end

app/models/container_type.rb
class ContainerType < ActiveRecord::Base
  acts_as_paranoid
end

app/models/high_score.rb
class HighScore < ActiveRecord::Base
end

app/models/inventory_item.rb
class InventoryItem < ActiveRecord::Base
  establish_connection DB_CONF
  self.table_name = 'InventoryItem'
end

app/models/item.rb
class Item < ActiveRecord::Base
  acts_as_paranoid
end

app/models/map_item.rb
class MapItem < ActiveRecord::Base
  self.table_name = 'map_item'
  has_many :pu_order_detail ,foreign_key: :InventoryItemID, primary_key: :ItemID
end

app/models/map_purchase.rb
class MapPurchase < ActiveRecord::Base
  has_many :purchase_order, foreign_key: :RefID, primary_key: :RefID
  has_many :map_item, foreign_key: :map_purchase_id
end

app/models/pu_order_detail.rb
class PuOrderDetail < ActiveRecord::Base
  establish_connection DB_CONF
  self.table_name = 'PuOrderDetail'

  belongs_to :purchase_order, foreign_key: :RefID
  has_one :item , foreign_key: :item_id, primary_key: :InventoryItemID
end

app/models/purchase_order.rb
class PurchaseOrder < ActiveRecord::Base
  establish_connection DB_CONF
  self.table_name = 'PUOrder'

  enum Status: ["Chưa thực hiện", "Đang thực hiện", "Hoàn thành" ]

  has_many :pu_order_detail, foreign_key: :RefID
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  establish_connection DB_CONF
  self.table_name = 'Unit'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/high_scores_controller.rb
class HighScoresController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  end

  def show
    @supplier = AccountObject.where(AccountObjectID: params[:id])
    @items = InventoryItem.all
    @selected_items = @supplier[0].item
    #binding.pry
  end

  def insert
     #binding.pry
    @list_items = InventoryItem.where(InventoryItemID: params[:list_items])
    @list_items.each do |item|
      params_create = {item_id: item.InventoryItemID,
                       item_code: item.InventoryItemCode,
                       supplier_id: params[:supplier_id]}
      Item.create(params_create)
    end
    redirect_to item_path(params[:supplier_id])
  end

  def suppliers
    @suppliers = AccountObject.all
  end
end

app/controllers/map_order_controller.rb
class MapOrderController < ApplicationController
  def index
    @purchase_order = PurchaseOrder.where(status: [0, 1]).order(:RefDate)
  end

  def create
    @list_order = PurchaseOrder.includes(:pu_order_detail).where(RefID: params[:list_orders])
  end

  def creates
    # binding.pry
    map_id = Time.now.strftime("%Y%d%m%H%M%S")
    params[:Pu].each do |pu|
      MapPurchase.create(map_id: map_id , RefID: pu[:RefID], date_map: Time.now.strftime("%Y-%d-%m %H:%M:%S %Z"))
      pu[:Item].each do |item|
        MapItem.create(ItemID: item[:InventoryItemID], map_purchase_id: MapPurchase.find_by(RefID: pu[:RefID]).id, quantity: item[:quantity]  )
      end
    end
  end

end

app/controllers/show_map_controller.rb
class ShowMapController < ApplicationController
  def index
    @list_map = MapPurchase.all.map(&:map_id).uniq
    if params[:list_map].nil?
      @list_order = MapPurchase.where( map_id: @list_map.first)
    else
      @list_order = MapPurchase.where( map_id: params[:list_map])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/high_scores_helper.rb
module HighScoresHelper
end

app/helpers/inventory_items_helper.rb
module InventoryItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/map_order_helper.rb
module MapOrderHelper

  def show_unit(unit_id)
    Unit.where(UnitID: unit_id)[0].try(:UnitName)
  end

  def volume(volume, quantity)
    volume = volume.nil? ? 0 : volume
    volume*quantity
  end

  def weight(weight, quantity)
    weight = weight.nil? ? 0 : weight
    weight*quantity
  end
end

app/helpers/purchase_orders_helper.rb
module PurchaseOrdersHelper
end

app/helpers/show_map_helper.rb
module ShowMapHelper
end

app/views/map_order/create.html.erb
<section class="content">
  <div class="wrapper">
<%= form_tag creates_map_order_index_path do %>

  <div class="panel panel-primary">
    <div class="panel-heading">mat hang</div>
      <div class="panel-body" style="max-height: 500px;overflow-y: scroll;">
        <div class="row-main panel-body">
      <% @list_order.each do |detail_pus|%>
      <div class="panel-heading">
        <h2 class="panel-title">
          <b style="font-size:16px;">Don Hang: <%= detail_pus.AccountObjectName%></b>
          <%= hidden_field_tag("Pu[][RefID]", detail_pus.RefID)%>
        </h3>
      </div>
      <p>Chi Tiet Don hang</p>
        <% detail_pus.pu_order_detail.each do |detail_pu|%>
        <div class="panel panel-default login-form">
              <div class="panel-heading">
                <h3 class="panel-title">
                  <b style="font-size:16px;">Mã hàng: <%= detail_pu.InventoryItemID%></b>
                  <%= hidden_field_tag("Pu[][Item][][InventoryItemID]", detail_pu.InventoryItemID)%>
                </h3>
              </div>
              <div class="panel-body">
                <div class="">
            <table style="width:90%;font-size:15px;">
              <tr>
                <td colspan="3">Tên hàng: <%= detail_pu.Description%></td>
              </tr>
              <tr>
                <td>Số lượng: <%= number_field_tag 'Pu[][Item][][quantity]', detail_pu.Quantity, class: "form-control quantity"  %></td>
                <td colspan="3">
                  Đơn vị tính:
                  <%= show_unit(detail_pu.UnitID) %>
                </td>
              </tr>
              <tr>
                <td>Thể tích: <div class="volume"><%= volume(detail_pu.item.try(:volume), detail_pu.Quantity)%> </div></td>
                <%= hidden_field_tag("volume_detail", detail_pu.item.try(:volume), {class: "volume_detail"})%>
                <td colspan="3">Khối lượng: <div class="weight">  <%= weight(detail_pu.item.try(:weight), detail_pu.Quantity)%></div></td>
                <%= hidden_field_tag("weight_detail", detail_pu.item.try(:weight), {class: "weight_detail"})%>
              </tr>
              <tr>
                <td>Số lượng nhận: <%= detail_pu.QuantityReceipt%></td>
              </tr>
            </table>
          </div>
              </div>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

<%= submit_tag "Save", class: "btn btn-primary", data: { confirm: "Are you sure?" } %>
<% end %>
The Tich: <div class="the_tich"></div>
Khoi Luong: <div class="khoi_luong"></div>
  </div>
</section>

app/views/map_order/index.html.erb
<section class="content">
  <div class="wrapper">
    <h1 align="center">Chọn Don hàng</h1>
    <div class="col-md-8">
      <h4>Multi-select</h4>
      <%= form_tag(map_order_index_path) do %>

        <%= select_tag 'list_orders', options_for_select(@purchase_order.collect{ |u| [u.AccountObjectName, u.RefID] }), multiple: true , id: :items%>

         <%= submit_tag( "SUBMIT" , class: "btn button" ) %>
      <% end %>
    </div>
    <p id="demo"></p>
  </div>
</section>

app/views/show_map/index.html.erb
<section class="content">
  <div class="wrapper">
  <%= form_tag show_map_index_path, :name => "switch_car",:method => :get do %>
    <div class="field">
        <label>Car Name:</label>
        <%= select_tag "list_map", options_for_select(@list_map, selected: params[:list_map]), { class: "form-control", :onchange => "this.form.submit()"}%>
    </div>

    <% end %>
  
  <br>
<%= form_tag creates_map_order_index_path do %>

  <div class="panel panel-primary">
    <div class="panel-heading">mat hang</div>
      <div class="panel-body" style="max-height: 500px;overflow-y: scroll;">
        <div class="row-main panel-body">
      <% @list_order.each do |detail_pus|%>
      <div class="panel-heading">
        <h2 class="panel-title">
          <b style="font-size:16px;">Don Hang: <%= detail_pus.purchase_order[0].try(:AccountObjectName)%></b>
        </h3>
      </div>
      <p>Chi Tiet Don hang</p>
        <% detail_pus.map_item.each do |detail_pu|%>
        <div class="panel panel-default login-form">
              <div class="panel-heading">
                <h3 class="panel-title">
                  <b style="font-size:16px;">Mã hàng: <%= detail_pu.pu_order_detail[0].InventoryItemID%></b>
                </h3>
              </div>
              <div class="panel-body">
                <div class="">
            <table style="width:90%;font-size:15px;">
              <tr>
                <td colspan="3">Tên hàng: <%= detail_pu.pu_order_detail[0].Description%></td>
              </tr>
              <tr>
                <td>Số lượng: <%= number_field_tag 'Pu[][Item][][quantity]', detail_pu.quantity, class: "form-control quantity"  %></td>
                <td colspan="3">
                  Đơn vị tính:
                  <%= show_unit(detail_pu.pu_order_detail[0].UnitID) %>
                </td>
              </tr>
              <tr>
                <td>Thể tích: <div class="volume"><%= volume(detail_pu.pu_order_detail[0].item.try(:volume), detail_pu.quantity)%> </div></td>
                <%= hidden_field_tag("volume_detail", detail_pu.pu_order_detail[0].item.try(:volume), {class: "volume_detail"})%>
                <td colspan="3">Khối lượng: <div class="weight">  <%= weight(detail_pu.pu_order_detail[0].item.try(:weight), detail_pu.quantity)%></div></td>
                <%= hidden_field_tag("weight_detail", detail_pu.pu_order_detail[0].item.try(:weight), {class: "weight_detail"})%>
              </tr>
            </table>
          </div>
              </div>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
The Tich: <div class="the_tich"></div>
Khoi Luong: <div class="khoi_luong"></div>
  </div>
</section>